<a href="https://colab.research.google.com/github/marufa181/CERTIFICATE/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Basics:

**Importing** **library**

In [76]:
import numpy as np

**Array** **Atrributes**

In [77]:
a = np.array([1,2,3]) # 1-D Array/ vector
a

array([1, 2, 3])

In [78]:
type(a)

numpy.ndarray

In [79]:
a.shape

(3,)

In [80]:
a.ndim

1

In [81]:
b = np.array([[1,2,3],
              [4,5,6]]) # 2-D Array/ Matrix
b

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
type(b)

numpy.ndarray

In [83]:
b.shape

(2, 3)

In [84]:
b.ndim

2

In [85]:
c = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]]]) # 3-D Array/ Tensor
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [86]:
type(c)

numpy.ndarray

In [87]:
c.shape

(1, 3, 3)

In [88]:
c.ndim

3

In [89]:
d = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],

              [[10,11,12],
               [13,14,15],
               [16,17,18]]])
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [90]:
d.shape

(2, 3, 3)

In [91]:
d.ndim

3

In [92]:
a.dtype

dtype('int64')

In [93]:
b.dtype

dtype('int64')

In [94]:
c.dtype

dtype('int64')

In [95]:
d.dtype

dtype('int64')

In [96]:
a.size, b.size, c.size, d.size  # determine how many elements are there in an array

(3, 6, 9, 18)

In [97]:
# how memory getting
a.nbytes, b.nbytes, c.nbytes, d.nbytes

(24, 48, 72, 144)

In [98]:
a.itemsize, b.itemsize, c.itemsize, d.itemsize

(8, 8, 8, 8)

In [99]:
a.data, b.data, c.data, d.data

(<memory at 0x7e764e620a00>,
 <memory at 0x7e764e57c220>)

**Array creation**

In [100]:
array1 = np.array([1,2,3], dtype = 'int')
array1

array([1, 2, 3])

In [101]:
array = np.zeros((2,2), dtype = 'float')
array

array([[0., 0.],
       [0., 0.]])

In [102]:
arr = np.zeros((3,3), dtype = 'int')
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [103]:
one = np.ones((3,3), dtype = 'int')
one

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [104]:
full = np.full((2,2), 5)
full

array([[5, 5],
       [5, 5]])

In [105]:
identity = np.identity(3,dtype='int')
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [106]:
eye = np.eye(3,3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [107]:
eye = np.eye(3,3,1)
eye

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [108]:
arange = np.arange(1,10,2) # range
arange

array([1, 3, 5, 7, 9])

In [109]:
linspace = np.linspace(1,10,5) # linear space
linspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [110]:
linspace = np.linspace(1,10,10) # linear space
linspace

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [111]:
linspace.size

10

In [112]:
linspace = np.linspace(1,100,50, dtype = 'int') # linear space
linspace

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100])

In [113]:
linspace.size

50

In [114]:
empty = np.empty((1,5))
empty

array([[ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]])

In [115]:
for i in range(5):
  empty[:,i] = i
empty

array([[0., 1., 2., 3., 4.]])

**Array Indexing and Slicing**

1.**Indexing**

In [116]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [117]:
arr1[0]

1

In [118]:
arr1[4]

5

In [119]:
arr1[-1] # last index

5

In [120]:
arr2 = np.random.randint(1,10, size= (3,3))
arr2

array([[4, 2, 6],
       [8, 5, 3],
       [6, 6, 3]])

In [121]:
arr2[0][0]

4

In [122]:
arr2[1][2]

3

In [123]:
arr3 = np.random.randint(1,10, size = (2,3,3))
arr3

array([[[5, 6, 8],
        [5, 9, 6],
        [7, 1, 1]],

       [[7, 6, 7],
        [5, 6, 3],
        [9, 8, 8]]])

In [124]:
arr3[0][0][1]

6

In [125]:
arr3[1][1][1]

6

2.**Slicing**

In [126]:
arr1

array([1, 2, 3, 4, 5])

In [127]:
# needed first 3 elements
print(arr1[0:3])


[1 2 3]


In [128]:
arr1[2:]

array([3, 4, 5])

In [129]:
arr2

array([[4, 2, 6],
       [8, 5, 3],
       [6, 6, 3]])

In [130]:
arr2[0:2,0:2]

array([[4, 2],
       [8, 5]])

In [131]:
arr2[1:,1:]

array([[5, 3],
       [6, 3]])

## Manipilating array shapes
   1.reshape()
   2.resize()
   3.flatten()
   4.revel()
   5.defining array shape

**1. reshape**

In [132]:
a = np.array([[1,2,3],
              [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [133]:
a.shape

(2, 3)

In [135]:
a_reshape = np.reshape(a,(3,2))
a_reshape

array([[1, 2],
       [3, 4],
       [5, 6]])

In [136]:
a_reshape.shape

(3, 2)

In [138]:
a_reshape = np.reshape(a,(3,3))
a_reshape

ValueError: cannot reshape array of size 6 into shape (3,3)

**2. resize()**

In [139]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [140]:
a.shape

(2, 3)

In [142]:
a_resize = np.resize(a,(4,3))
a_resize

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [144]:
a_resize = np.resize(a,(3,2))
a_resize

array([[1, 2],
       [3, 4],
       [5, 6]])

**3. revel**

In [145]:
a = np.random.randint(1,10, size = (2,3))
a

array([[5, 9, 8],
       [4, 3, 8]])

In [146]:
a_reveled = np.ravel(a)
a_reveled

array([5, 9, 8, 4, 3, 8])

In [147]:
a_reveled.shape


(6,)

In [150]:
a_reveled[0]

5

In [152]:
a_reveled[0]=0
a_reveled

array([0, 9, 8, 4, 3, 8])

**4. flatten()**

In [153]:
a

array([[0, 9, 8],
       [4, 3, 8]])

In [154]:
a_flattened = a.flatten() # Return a copy of the array, always allocates a new memory
a_flattened

array([0, 9, 8, 4, 3, 8])

In [155]:
a_flattened[0]=100
a_flattened

array([100,   9,   8,   4,   3,   8])

In [156]:
a

array([[0, 9, 8],
       [4, 3, 8]])

**5. defining an array shape**

In [157]:
a

array([[0, 9, 8],
       [4, 3, 8]])

In [158]:
a.shape = (3,2)
a

array([[0, 9],
       [8, 4],
       [3, 8]])

In [159]:
a.shape = (5,2)

ValueError: cannot reshape array of size 6 into shape (5,2)

# Stacking

** Horizontal stack**

In [160]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [161]:
b = 2*a
b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [162]:
np.hstack((a,b))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [163]:
np.column_stack((a,b))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [164]:
np.concatenate((a,b), axis = 1)

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

** Vertical stack**

In [165]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [166]:
np.row_stack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [167]:
np.concatenate((a,b), axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

**Depth stack**

In [168]:
np.dstack((a,b))

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18]]])